# Generated by Django 5.2.6 on 2025-09-30 07:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('ASSET', 'Asset'), ('LIAB', 'Liability'), ('INCOME', 'Income'), ('EXP', 'Expense'), ('EQUITY', 'Equity')], max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('amount', models.BigIntegerField(help_text='minor units, e.g., cents')),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='REQUESTED', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='ledger.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='ledger.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'created_at'], name='ledger_post_account_658090_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='posting_amount_nonzero')],
            },
        ),
    ]
